### ISSUE TITLE
Ошибка при установке

### ISSUE THREAD

**Issue by porcelanosa** [socialist/yii2-admin-lte#2]
Выскакивает ошибка
Your requirements could not be resolved to an installable set of packages.                                           

  Problem 1  
    - Installation request for socialist/yii2-admin-lte @dev -> satisfiable by socialist/yii2-admin-lte[dev-master]. 
    - socialist/yii2-admin-lte dev-master requires bower/adminlte \* -> no matching package found.                    

Potential causes:                                                                                                    
- A typo in the package name  
- The package is not available in a stable-enough version according to your minimum-stability setting  
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.  

Read http://getcomposer.org/doc/articles/troubleshooting.md for further common problems.                           

Installation failed, reverting ./composer.json to its original content.                                              

Похоже они переименовали bower adminlte в bower admin-lte

**Comment by socialist** [comment]
AdminLTE через bower доступен и так (adminlte) и так (admin-lte). Ошибка моя была, не правильно прописал зависимости.
Сейчас исправил, все должно работать.

**Comment by porcelanosa** [comment]
да всё установилось - подтверждаю
